/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clientetcp;

import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author correia
 */
public class SintomasMedicos extends javax.swing.JFrame {
    private ClienteTcp client;

    /**
     * Creates new form SintomasMedicos
     */
    public SintomasMedicos(){
        initComponents();
        client = new ClienteTcp();
        loadSymptoms();
        loadIllness();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcao = new javax.swing.ButtonGroup();
        treinamento = new javax.swing.JToggleButton();
        avaliacao = new javax.swing.JToggleButton();
        producao = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sintomas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        doencas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        prompt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcao.add(treinamento);
        treinamento.setText("TREINAMENTO");
        treinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinamentoActionPerformed(evt);
            }
        });

        opcao.add(avaliacao);
        avaliacao.setText("AVALIAÇÃO");
        avaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliacaoActionPerformed(evt);
            }
        });

        opcao.add(producao);
        producao.setText("PRODUÇÃO");
        producao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producaoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("SINTOMAS");

        jScrollPane2.setViewportView(sintomas);

        jLabel2.setText("DOENÇA");

        prompt.setColumns(20);
        prompt.setRows(5);
        jScrollPane1.setViewportView(prompt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(treinamento)
                            .addComponent(avaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(producao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(doencas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(treinamento)
                        .addGap(24, 24, 24)
                        .addComponent(avaliacao)
                        .addGap(24, 24, 24)
                        .addComponent(producao)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinamentoActionPerformed
        // TODO add your handling code here:
        this.doencas.setEnabled(true);
    }//GEN-LAST:event_treinamentoActionPerformed

    private void producaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producaoActionPerformed
        // TODO add your handling code here:
        this.doencas.setEnabled(false);
    }//GEN-LAST:event_producaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<String> sintomasAtual = this.sintomas.getSelectedValuesList();
        String doencaAtual = (String)this.doencas.getSelectedItem();
        String result;

        // training
        if(treinamento.isSelected()){
            String msg = "1;"+client.getNomeDNS()+";"+sintomasAtual+";"+doencaAtual;

            try {
                result = this.client.enviarMensagem(msg);
                prompt.setText("Doença "+doencaAtual+" treinada:\n"+result);
            } catch (UnknownError | IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+". Erro no treinamento");
            }
        }else if(avaliacao.isSelected()){
            String msg = "2;"+client.getNomeDNS()+";"+sintomasAtual+";"+doencaAtual;
        
            try {
                result = this.client.enviarMensagem(msg);
                prompt.setText(result);
            } catch (UnknownError | IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+". Erro na avaliacao");
            }
        }else if(producao.isSelected()){
            String msg = "3;"+client.getNomeDNS()+";"+sintomasAtual;
        
            try {
                result = this.client.enviarMensagem(msg);
                prompt.setText(result);
            } catch (UnknownError | IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+". Erro na producao");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Voce precisa selecionar algum modo: TREINAMENTO, AVALIACAO, PRODUCAO");
        }
        
        System.out.println(sintomasAtual);
        System.out.println(doencaAtual);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void avaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliacaoActionPerformed
        // TODO add your handling code here:
        this.doencas.setEnabled(true);
    }//GEN-LAST:event_avaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SintomasMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SintomasMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SintomasMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SintomasMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SintomasMedicos().setVisible(true);
            }
        });
    }
    
    public void setComboBox(JComboBox<String> comboBox, String[] itens) {
        comboBox.removeAllItems();

        for (String item : itens) {
            comboBox.addItem(item);
        }
    }
    
    //carregando sintomas
    private void loadSymptoms(){
        DefaultListModel model = new DefaultListModel();
        String msg = "4;"+client.getNomeDNS();
        String[] result;
        
        try {
            this.sintomas.setModel(model);
            result = this.client.enviarMensagem(msg).split(",");
            for(String str : result){model.addElement(str);}
        } catch (UnknownError | IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+". Não Inicializou os sintomas");
        }
    }
    
    //carregando doenças
    private void loadIllness(){
        String msg = "5;"+client.getNomeDNS();
        String[] result;
        
        try {
            result = this.client.enviarMensagem(msg).split(",");
            setComboBox(doencas, result);
        } catch (UnknownError | IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+". Não Inicializou as Doencas");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton avaliacao;
    private javax.swing.JComboBox<String> doencas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup opcao;
    private javax.swing.JToggleButton producao;
    private javax.swing.JTextArea prompt;
    private javax.swing.JList<String> sintomas;
    private javax.swing.JToggleButton treinamento;
    // End of variables declaration//GEN-END:variables
}
